S0LStar/SOLStar

- solstar/dev-dist/sw.js
- solstar/src/components/login/LoginContainer.css
- solstar/src/components/login/LoginContainer.jsx
- solstar/src/components/mypage/MyContainer.jsx
- solstar/src/components/wallet/WalletContainer.jsx
- solstar/src/components/zzim/ZzimContainer.jsx
- solstar/src/pages/LoginPage.jsx
- solstar/src/pages/MyPage.jsx
- solstar/src/pages/WalletPage.jsx
- solstar/src/pages/ZzimPage.jsx
- solstar/src/routes/AppRoutes.jsx
Description
API 연결을 제외한 로그인 페이지 구현했습니다.
> [#13] 로그인 페이지 구현

- backend/solstar/build.gradle
- backend/solstar/src/main/java/com/shinhan/solstar/domain/account/entity/Account.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/account/model/repository/AccountRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/agency/entity/Agency.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/agency/model/repository/AgencyRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/controller/AuthController.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/request/LoginRequest.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/request/SignupRequest.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/response/LoginResponse.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/response/RefreshResponse.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/model/service/AuthService.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/user/controller/UserController.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/user/entity/User.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/user/model/repository/UserRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/auth/CustomUserDetailsService.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/auth/jwt/JwtAuthenticationFilter.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/auth/jwt/JwtUtil.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/config/SecurityConfig.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/config/SwaggerConfig.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/exception/CustomException.java
> Feature/31 회원관리 기능

- frontend/solstar/src/components/common/WideButton.jsx
- frontend/solstar/src/components/funding/fundingRegist/FundingRegist.jsx
- frontend/solstar/src/components/main/MainContainer.css
- frontend/solstar/src/routes/AppRoutes.jsx
> [#7] 펀딩 생성 페이지 디자인 수정

- backend/solstar/build.gradle
- backend/solstar/src/main/java/com/shinhan/solstar/domain/account/entity/Account.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/account/model/repository/AccountRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/agency/entity/Agency.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/agency/model/repository/AgencyRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/controller/AuthController.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/request/LoginRequest.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/request/SignupRequest.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/response/LoginResponse.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/dto/response/RefreshResponse.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/auth/model/service/AuthService.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/user/controller/UserController.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/user/entity/User.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/user/model/repository/UserRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/auth/CustomUserDetailsService.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/auth/jwt/JwtAuthenticationFilter.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/auth/jwt/JwtUtil.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/config/SecurityConfig.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/config/SwaggerConfig.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/exception/CustomException.java
> Revert "Revert "develop으로 develop-be 머지""

- backend/solstar/.gitignore
- backend/solstar/src/main/java/com/shinhan/solstar/domain/board/dto/request/BoardCreateRequestDto.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/board/dto/request/BoardUpdateRequestDto.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/board/dto/response/BoardResponseDto.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/board/entity/Board.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/board/entity/BoardType.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/board/model/repository/BoardRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/board/model/service/BoardService.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/controller/FundingController.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/dto/request/FundingCreateRequestDto.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/dto/response/FundingContentResponseDto.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/dto/response/FundingDetailResponseDto.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/dto/response/FundingResponseDto.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/entity/Funding.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/model/repository/FundingRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/model/service/FundingService.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/funding/model/service/FundingServiceImpl.java
- backend/solstar/src/main/java/com/shinhan/solstar/domain/user/model/repository/UserRepository.java
- backend/solstar/src/main/java/com/shinhan/solstar/global/exception/CustomException.java
- backend/solstar/src/main/resources/application.properties
- 펀딩 내용 조회 기능
- 펀딩 공지사항 생성 기능
- 펀딩 공지사항 조회 기능
- 펀딩 공지사항 수정 기능
- 펀딩 공지사항 삭제 기능
- 펀딩 금액 달성 시 상태 변경
- 메인 페이지 내 펀딩 조회 기능 일부 구현
> [#25] 펀딩 기능 구현

- frontend/solstar/src/components/funding/search/FundingSearchResult.css
- frontend/solstar/src/components/funding/search/FundingSearchResult.jsx
- frontend/solstar/src/components/main/MainContainer.css
> Design: 메인 페이지 css 수정

- backend/build.gradle
- backend/src/main/java/com/common/solstar/SolStarApplication.java
- backend/src/main/java/com/common/solstar/domain/agency/controller/AgencyController.java
- backend/src/main/java/com/common/solstar/domain/agency/model/repository/AgencyRepository.java
- backend/src/main/java/com/common/solstar/domain/agency/model/service/AgencyService.java
- backend/src/main/java/com/common/solstar/domain/agency/model/service/AgencyServiceImpl.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/response/FundingAgencyResponseDto.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/response/FundingDetailResponseDto.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingServiceImpl.java
- backend/src/main/java/com/common/solstar/domain/fundingAgency/entity/FundingAgency.java
- backend/src/main/java/com/common/solstar/domain/fundingAgency/model/repository/FundingAgencyRepository.java
- backend/src/main/java/com/common/solstar/domain/fundingJoin/entity/FundingJoin.java
- backend/src/main/java/com/common/solstar/global/exception/CustomException.java
- backend/src/main/resources/application.properties
인증 펀딩 중 아직 미승인 상태인 펀딩 기준
- 펀딩 인증 요청 조회
- 펀딩 인증 요청 승인
- 펀딩 인증 요청 거절
> [#53] 소속사 기능 개발

- frontend/solstar/dev-dist/sw.js
- frontend/solstar/src/components/mypage/MyContainer.css
- frontend/solstar/src/components/mypage/MyContainer.jsx
- frontend/solstar/src/components/zzim/ZzimContainer.css
- frontend/solstar/src/components/zzim/ZzimContainer.jsx
> [#16] 회원가입 페이지 구현

- backend/src/main/java/com/common/solstar/domain/agency/controller/AgencyController.java
- backend/src/main/java/com/common/solstar/domain/artist/controller/ArtistController.java
- backend/src/main/java/com/common/solstar/domain/artist/dto/response/ArtistSearchResponseDto.java
- backend/src/main/java/com/common/solstar/domain/artist/dto/response/LikeArtistResponseDto.java
- backend/src/main/java/com/common/solstar/domain/board/dto/request/BoardCreateRequestDto.java
- backend/src/main/java/com/common/solstar/domain/board/dto/request/BoardUpdateRequestDto.java
- backend/src/main/java/com/common/solstar/domain/board/dto/response/BoardResponseDto.java
- backend/src/main/java/com/common/solstar/domain/board/entity/Board.java
- backend/src/main/java/com/common/solstar/domain/board/model/service/BoardService.java
- backend/src/main/java/com/common/solstar/domain/funding/controller/FundingController.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/response/FundingDetailResponseDto.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/response/FundingResponseDto.java
- backend/src/main/java/com/common/solstar/domain/funding/entity/Funding.java
- backend/src/main/java/com/common/solstar/domain/funding/model/repository/FundingRepository.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingMonitoringService.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingServiceImpl.java
- backend/src/main/java/com/common/solstar/domain/fundingJoin/model/repository/FundingJoinRepository.java
- backend/src/main/resources/application.properties
**기능**
- 펀딩 참여 시 정보 업데이트 및 마감, 삭제 로직 구현
**리팩토링**
- 펀딩 상세 조회 response dto 수정 (펀딩 주최자 및 참여자 여부 `joinStatus` 로 표기)
- 선호 펀딩 아티스트 전체 조회 등의 데이터 태그 추가
- 펀딩 공지 내용에 전반적으로 image 추가
- 펀딩 공지사항에 전체 조회 / 상세 조회 시 펀딩 주최자 여부 상태값 (`isHost`) 추가
> [#63] 펀딩 관련 리팩토링

- frontend/solstar/src/components/mypage/AgencyMyPageContainer.css
- frontend/solstar/src/components/mypage/AgencyMyPageContainer.jsx
- frontend/solstar/src/components/mypage/MyArtist.css
- frontend/solstar/src/components/mypage/MyArtist.jsx
- frontend/solstar/src/components/mypage/MyArtistFunding.css
- frontend/solstar/src/components/mypage/MyArtistFunding.jsx
- frontend/solstar/src/components/mypage/MyContainer.css
- frontend/solstar/src/components/mypage/MyContainer.jsx
- frontend/solstar/src/components/mypage/RequestFunding.css
- frontend/solstar/src/components/mypage/RequestFunding.jsx
- frontend/solstar/src/routes/AppRoutes.jsx
> [#18] 소속사 마이페이지 구현

- backend/src/main/java/com/common/solstar/domain/agency/controller/AgencyController.java
- backend/src/main/java/com/common/solstar/domain/agency/model/service/AgencyService.java
- backend/src/main/java/com/common/solstar/domain/agency/model/service/AgencyServiceImpl.java
- 기존 소속사 관련 기능에 로그인된 계정이 소속사 계정인지 확인하는 로직 적용
> [#81] 소속사 계정 검증 로직 적용

- frontend/solstar/src/components/funding/detail/FundingDetail.css
- frontend/solstar/src/components/funding/detail/FundingDetail.jsx
- frontend/solstar/src/components/funding/detail/FundingNotiList.css
- frontend/solstar/src/components/funding/detail/FundingNoticeRegist.css
- frontend/solstar/src/components/funding/detail/FundingNoticeRegist.jsx
- frontend/solstar/src/components/funding/detail/FundingPayment.jsx
> [#8] 펀딩 상세 페이지 구현

- frontend/src/components/mypage/RequestFunding.css
>  [#18] 소속사 마이페이지 인증 펀딩 요청 버튼 css 수정

- .env.local
- LoginForm;.jsx
- authSlide.js
- axiosInstance.js
- frontend/src/components/login/LoginContainer.jsx
- frontend/src/redux/Redux.js
- frontend/src/redux/slices/authSlice.js
- frontend/src/routes/AppRoutes.jsx
- frontend/src/routes/PrivateRoutes.jsx
- privateRoute.jsx
> [#13] 로그인페이지 로그인 구현

- frontend/src/components/login/LoginContainer.jsx
- frontend/src/components/mypage/MyContainer.jsx
- frontend/src/main.jsx
- frontend/src/util/AxiosInstance.js
> [#13] 로그인 저장 위치 수정

- frontend/src/components/mypage/MyContainer.css
- frontend/src/components/mypage/MyContainer.jsx
> [#17] 사용자 마이페이지 구현

- frontend/dev-dist/sw.js
- frontend/src/components/login/LoginContainer.css
- frontend/src/components/login/LoginContainer.jsx
> [#13] 소속사 로그인 구현

- frontend/src/components/mypage/MyContainer.jsx
> [#17] 사용자 마이페이지 로그아웃(API 빼고) 구현

- backend/src/main/java/com/common/solstar/domain/account/model/repository/AccountRepository.java
- backend/src/main/java/com/common/solstar/domain/funding/controller/FundingController.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/DonateRequest.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/InquireAccountRequestDto.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/TransferTotalAmountRequest.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/response/TransferTotalAmountResponse.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingMonitoringService.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingService.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingServiceImpl.java
- backend/src/main/java/com/common/solstar/global/exception/CustomException.java
- 펀딩 계좌 생성 시 총 모금액 입금
- 펀딩 완료 시 계좌 잔여 금액 기부
> [#101] 펀딩 정산금 사용 완료 기능

- backend/src/main/java/com/common/solstar/domain/artist/model/service/ArtistServiceImpl.java
- backend/src/main/java/com/common/solstar/domain/board/model/service/BoardService.java
- backend/src/main/java/com/common/solstar/domain/funding/controller/FundingController.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/TransferRefundRequest.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/TransferTotalAmountRequest.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/UseBudgetRequest.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingMonitoringService.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingService.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingServiceImpl.java
- backend/src/main/java/com/common/solstar/global/exception/CustomException.java
- backend/src/main/resources/application.properties
**[기능 구현]**
- 펀딩 정산금 이체 기능 구현
**[추가 수정사항]**
- create 메서드 트랜잭션 처리
- 전반적인 금융 api에 사용되는 userKey 프로젝트 기획의도에 맞춰 수정
> [#125] 펀딩 정산 후 이체 기능 구현

- frontend/src/redux/Redux.js
- frontend/src/redux/slices/authSlice.js
- frontend/src/util/AxiosInstance.js
> [#13] 로그인 cookie 적용

- frontend/src/App.jsx
- frontend/src/components/login/LoginContainer.css
- frontend/src/components/mypage/MyContainer.jsx
- frontend/src/routes/AppRoutes.jsx
> [#13] 로그인 새로고침 및 로그인 회원가입 하단바 숨김 처리

- frontend/src/components/login/LoginContainer.jsx
- frontend/src/components/signup/accountRegist/CreateAccount.jsx
> [#14] 로그인 기다림 적용 및 회원가입 페이지 구현

- frontend/.gitignore
- frontend/src/components/signup/accountRegist/AccountRegistration.jsx
- frontend/src/components/signup/accountRegist/AccountVerification.jsx
- frontend/src/components/signup/accountRegist/ResetPassword.jsx
> [#14] 회원가입페이지

- frontend/src/App.jsx
> [#14] 하단 바 수정

- frontend/src/components/wallet/WalletContainer.jsx
> [#15] 지갑 페이지 구현

- frontend/src/components/mypage/ViewProfile.jsx
> [#17] 내 정보 보기 기본 이미지 수정

- frontend/dev-dist/sw.js
- frontend/src/components/mypage/MyContainer.jsx
> [#17] 로그아웃 시 localstorage 삭제

- frontend/src/components/zzim/ZzimContainer.jsx
> [#16] 찜페이지

- frontend/src/components/mypage/CreatedFunding.jsx
- frontend/src/components/wallet/FundingWalletDetail.css
- frontend/src/components/wallet/FundingWalletDetail.jsx
- frontend/src/components/wallet/FundingWalletItem.jsx
> [#15] 지갑페이지

- backend/build.gradle
- backend/src/main/java/com/common/solstar/domain/user/entity/User.java
- backend/src/main/resources/application.properties
> [#124] 서버 DB 연결

- frontend/src/components/mypage/MyContainer.jsx
- frontend/src/components/mypage/RequestFunding.jsx
> [#17] 소속사 펀딩 승인 거절 구현

- backend/src/main/java/com/common/solstar/domain/funding/entity/Funding.java
> [#215] 인증 펀딩 중에서 삭제된 펀딩 숨김처리

- frontend/src/components/mypage/MyContainer.jsx
- frontend/src/components/mypage/ViewProfile.jsx
- frontend/src/components/signup/accountRegist/AccountRegistration.jsx
- frontend/src/components/signup/accountRegist/CreateAccount.jsx
> [#17] 마이페이지

- backend/src/main/java/com/common/solstar/domain/artist/controller/ArtistController.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/FundingCreateRequestDto.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/request/FundingUpdateRequestDto.java
- backend/src/main/java/com/common/solstar/domain/funding/entity/Funding.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingServiceImpl.java
- backend/src/main/java/com/common/solstar/global/util/ImageUtil.java
- 아티스트 사진 불러오기 기능 구현 및 펀딩 사진 기능 일부 구현
> [#215] 아티스트 사진 불러오기 기능 구현 및 펀딩 사진 기능 일부 구현

- backend/src/main/java/com/common/solstar/domain/artist/controller/ArtistController.java
- backend/src/main/java/com/common/solstar/domain/artist/entity/Artist.java
- backend/src/main/java/com/common/solstar/domain/artist/model/service/ArtistServiceImpl.java
> [#215] 아티스트 사진 불러오기 구현

- backend/src/main/java/com/common/solstar/domain/artist/controller/ArtistController.java
- backend/src/main/java/com/common/solstar/domain/board/dto/request/BoardCreateRequestDto.java
- backend/src/main/java/com/common/solstar/domain/board/entity/Board.java
- backend/src/main/java/com/common/solstar/domain/board/model/service/BoardService.java
- backend/src/main/java/com/common/solstar/domain/funding/dto/response/FundingDetailResponseDto.java
- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingServiceImpl.java
- backend/src/main/java/com/common/solstar/global/util/ImageUtil.java
> [#215] 사진 등록 및 호출

- backend/src/main/java/com/common/solstar/domain/funding/model/service/FundingServiceImpl.java
> [#274] 펀딩 사진 수정

- backend/src/main/java/com/common/solstar/domain/auth/controller/AuthController.java
- backend/src/main/java/com/common/solstar/domain/auth/dto/request/SignupRequest.java
- backend/src/main/java/com/common/solstar/domain/auth/model/service/AuthService.java
- backend/src/main/java/com/common/solstar/domain/user/controller/UserController.java
- backend/src/main/java/com/common/solstar/domain/user/model/service/UserService.java
- 회원가입 시 MultipartFIle 형태로 프로필 사진 업로드 구현
- 프로필 사진 수정 기능 구현
> [#299] 사용자 프로필 사진 관련 기능 수정
